/**
 * The settings page's strings, in both languages the shell offers.
 *
 * Key convention, and the one rule worth keeping: a switch's key is its Config field name, so
 * `toggle.<field>` and `toggle.<field>.desc`. The ten switches ARE the ten volatile fields, and a
 * key that drifts from its field name is the kind of bug nobody notices until a user reads a page of
 * identifiers. Everything else is grouped by the panel that uses it: `page.`, `tab.`, `label.`,
 * `filter.`, `scope.`, `status.`, `action.`, `pref.`, `mem.`, `add.`, `daily.`, `data.`.
 *
 * A missing key is not a crash: `translatorOf` falls back to the key itself, so a gap shows up as
 * `mem.list.empty` on screen rather than as a blank page. `tests/dict-keys.test.ts` is what keeps
 * that from happening in the first place.
 */

export const ZH: Record<string, string> = {
	"nav.title": "记忆与规则",
	"page.title": "记忆与规则",
	"page.subtitle": "跨会话长期记忆与每次回答前的行为准则。",
	"page.no-connection": "当前页面无法连接宿主：记忆数据不可用，但本地偏好仍可查看。",
	"tab.pref": "偏好",
	"tab.mem": "记忆",
	"tab.add": "新建",
	"tab.daily": "日志",
	"tab.data": "数据",
	"label.unavailable": "当前宿主不支持此设置项。",
	"label.readonly": "此项由部署配置固定，不可在此修改。",
	"label.loading": "读取中…",
	"filter.all": "全部",
	"scope.identity": "身份",
	"scope.global": "全局",
	"scope.project": "项目",
	"scope.daily": "日志",
	"status.active": "生效",
	"status.outdated": "过期",
	"status.archived": "归档",
	"status.pending": "待定",
	"action.save": "保存",
	"action.saving": "保存中…",
	"action.discard": "放弃修改",
	"action.saveFailed": "保存失败",
	"toggle.rulesEnabled": "启用行为引导规则",
	"toggle.rulesEnabled.desc": "每次对话开始前注入规则段落，来自全局与项目两级规则目录。",
	"toggle.memoryEnabled": "启用长期记忆",
	"toggle.memoryEnabled.desc": "关闭后不再读写记忆，也不注册对话工具。",
	"toggle.projectMemoryEnabled": "启用项目记忆",
	"toggle.projectMemoryEnabled.desc": "按 git 仓库根目录隔离，worktree 之间共享。",
	"toggle.dailyLogEnabled": "记录每日日志",
	"toggle.dailyLogEnabled.desc": "在一轮对话结束时写入当天日志。",
	"toggle.indexInjectionEnabled": "常驻索引注入",
	"toggle.indexInjectionEnabled.desc": "每轮注入索引（仅名称与关键词），保持前缀缓存稳定。",
	"toggle.cardInjectionEnabled": "按轮相关卡片",
	"toggle.cardInjectionEnabled.desc": "根据当前问题检索并注入最相关的若干条记忆。",
	"toggle.constraintInjectionEnabled": "硬性约束注入",
	"toggle.constraintInjectionEnabled.desc": "把硬性约束通过运行时上下文通道注入。",
	"toggle.tailReminderEnabled": "末尾记忆核对提醒",
	"toggle.tailReminderEnabled.desc": "在提示词末尾追加一句核对提醒；稳定不变，故可缓存。",
	"toggle.distillEnabled": "自动蒸馏",
	"toggle.distillEnabled.desc": "对话结束时运行零 LLM 的规则蒸馏流程。",
	"pref.group.write": "写记忆",
	"pref.group.write.desc": "哪些内容允许进入长期记忆。",
	"pref.group.inject": "注入",
	"pref.group.inject.desc": "每一轮向模型注入什么，以及注入多少。",
	"pref.group.rules": "规则",
	"pref.group.rules.desc": "行为引导规则的来源。",
	"pref.no-service": "当前宿主没有提供偏好设置服务，此页只能查看，无法保存。",
	"pref.unavailable": "该插件的偏好设置当前不可用。",
	"pref.loading": "正在读取宿主配置…",
	"pref.ephemeral": "宿主以内存模式提供设置：修改在本次运行内生效，重启后恢复。",
	"pref.saved": "已保存",
	"pref.dirs": "额外规则目录",
	"pref.dirs.desc": "除全局与项目规则目录外，额外扫描这些目录中的规则文件。",
	"pref.dirs.label": "目录列表",
	"pref.dirs.placeholder": "每行一个目录，支持 ~ 开头",
	"pref.reset": "恢复默认",
	"pref.resetDone": "已恢复默认",
	"mem.list.title": "记忆列表",
	"mem.list.desc": "按存储顺序浏览；带搜索词时改用检索排序，与对话中看到的排序一致。",
	"mem.list.empty": "没有符合条件的记忆。",
	"mem.search": "搜索",
	"mem.search.placeholder": "输入关键词后按检索排序",
	"mem.filter.scope": "层级",
	"mem.filter.status": "状态",
	"mem.filter.project": "项目",
	"mem.total": "共",
	"mem.more": "加载更多",
	"mem.pin": "置顶",
	"mem.unpin": "取消置顶",
	"mem.pinned": "已置顶",
	"mem.unpinned": "已取消置顶",
	"mem.edit": "编辑",
	"mem.archive": "归档",
	"mem.archived": "已归档",
	"mem.saved": "已保存",
	"mem.field.title": "标题",
	"mem.field.text": "内容",
	"mem.field.tags": "标签",
	"mem.field.tags.desc": "用逗号分隔；标签会出现在面板的标签表里。",
	"add.title": "新建记忆",
	"add.desc": "与对话中的 remember 工具走同一条写入路径：同样的去重、同样的四态合并。",
	"add.field.title": "标题（可空）",
	"add.field.title.placeholder": "留空则按内容自动起标题",
	"add.field.text": "要记住什么",
	"add.field.text.desc": "写清事实与结论即可，蒸馏不需要完整句子。",
	"add.field.scope": "写入层级",
	"add.field.scope.desc": "项目层需要先选择项目；身份层不在此处开放。",
	"add.field.project.pick": "请选择项目",
	"add.field.pinned": "置顶",
	"add.field.pinned.desc": "置顶的记忆在索引里优先出现，不会被自动清理。",
	"add.saved": "已写入",
	"add.note": "面板不会调用模型：写什么就存什么，是否替换由存储层的合并规则决定。",
	"add.decision": "合并结果",
	"add.superseded": "替代",
	"daily.title": "每日日志",
	"daily.desc": "第四层记忆：一轮对话结束时自动追加的内容，也可以在这里手动补记。",
	"daily.field.date": "日期",
	"daily.field.project": "项目",
	"daily.field.project.desc": "留空则查看全局日志。",
	"daily.empty": "这一天还没有日志。",
	"daily.entries": "条目",
	"daily.append": "补记",
	"daily.append.desc": "每行一条；空行会被忽略。",
	"daily.field.entry": "要补记的内容",
	"daily.field.entry.desc": "一行一条，按时间顺序追加。",
	"daily.saved": "已写入日志",
	"data.export.title": "导出 Markdown",
	"data.export.desc": "SQLite 是唯一的存储格式，Markdown 只用于导出与人工阅读。",
	"data.export.archived": "包含归档与过期条目",
	"data.export.archived.desc": "默认只导出仍然生效的记忆。",
	"data.export.build": "生成",
	"data.export.download": "下载",
	"data.export.ready": "已生成",
	"data.import.title": "从其他工具导入",
	"data.import.desc": "按内容形态识别来源：ChatGPT、claude.ai、Claude Code、ZCode、WorkBuddy 等。",
	"data.import.path": "路径",
	"data.import.path.desc": "导出目录或 zip 文件；可以先用预演看清会发生什么。",
	"data.import.path.placeholder": "例如 C:\\Users\\me\\.workbuddy",
	"data.import.dry": "仅预演",
	"data.import.dry.desc": "只扫描与判定，不写入任何内容。",
	"data.import.scope": "导入层级",
	"data.import.preview": "预演",
	"data.import.run": "开始导入",
	"data.import.done": "导入完成",
	"data.report.ok": "成功",
	"data.report.failed": "未能识别",
	"data.report.dry": "预演",
	"data.report.truncated": "已截断",
	"data.field.scanned": "扫描",
	"data.field.considered": "参与判定",
	"data.field.known": "已存在",
	"data.field.written": "写入",
	"data.field.wouldWrite": "将写入",
	"data.field.merged": "合并",
	"data.field.updated": "更新",
	"data.field.ignored": "忽略",
	"data.field.rejected": "拒绝",
	"data.field.oversized": "超长",
	"data.field.logged": "写入日志"
};

export const EN: Record<string, string> = {
	"nav.title": "Memory & Rules",
	"page.title": "Memory & Rules",
	"page.subtitle": "Cross-session long-term memory, and the rules applied before every answer.",
	"page.no-connection": "This page cannot reach the Host: memory data is unavailable, but local preferences can still be inspected.",
	"tab.pref": "Preferences",
	"tab.mem": "Memories",
	"tab.add": "New",
	"tab.daily": "Log",
	"tab.data": "Data",
	"label.unavailable": "This host does not offer this setting.",
	"label.readonly": "Fixed by deployment configuration; not editable here.",
	"label.loading": "Loading…",
	"filter.all": "All",
	"scope.identity": "Identity",
	"scope.global": "Global",
	"scope.project": "Project",
	"scope.daily": "Log",
	"status.active": "Active",
	"status.outdated": "Outdated",
	"status.archived": "Archived",
	"status.pending": "Pending",
	"action.save": "Save",
	"action.saving": "Saving…",
	"action.discard": "Discard",
	"action.saveFailed": "Save failed",
	"toggle.rulesEnabled": "Enable behavioural rules",
	"toggle.rulesEnabled.desc": "Inject the rules section before each conversation, merged from the global and project rule directories.",
	"toggle.memoryEnabled": "Enable long-term memory",
	"toggle.memoryEnabled.desc": "When off, memories are neither read nor written and the conversational tools are not registered.",
	"toggle.projectMemoryEnabled": "Enable project memory",
	"toggle.projectMemoryEnabled.desc": "Isolated per git repository root, shared across its worktrees.",
	"toggle.dailyLogEnabled": "Record a daily log",
	"toggle.dailyLogEnabled.desc": "Write the day’s log when a turn ends.",
	"toggle.indexInjectionEnabled": "Resident index injection",
	"toggle.indexInjectionEnabled.desc": "Inject the index every turn — names and keywords only, so the prefix cache stays stable.",
	"toggle.cardInjectionEnabled": "Per-turn relevance card",
	"toggle.cardInjectionEnabled.desc": "Retrieve and inject the memories most relevant to the current question.",
	"toggle.constraintInjectionEnabled": "Hard-constraint injection",
	"toggle.constraintInjectionEnabled.desc": "Inject hard constraints through the runtime-context channel.",
	"toggle.tailReminderEnabled": "Tail memory-check reminder",
	"toggle.tailReminderEnabled.desc": "Append one memory-check line at the end of the prompt; stable, therefore cacheable.",
	"toggle.distillEnabled": "Automatic distillation",
	"toggle.distillEnabled.desc": "Run the zero-LLM rule pipeline when a conversation ends.",
	"pref.group.write": "Writing memories",
	"pref.group.write.desc": "What is allowed into long-term memory.",
	"pref.group.inject": "Injection",
	"pref.group.inject.desc": "What is injected into every turn, and how much.",
	"pref.group.rules": "Rules",
	"pref.group.rules.desc": "Where the behavioural rules come from.",
	"pref.no-service": "This host does not provide the preferences service, so this page is read-only.",
	"pref.unavailable": "This plugin’s preferences are currently unavailable.",
	"pref.loading": "Reading the host configuration…",
	"pref.ephemeral": "The host serves settings in memory mode: changes last for this run and are reset on restart.",
	"pref.saved": "Saved",
	"pref.dirs": "Extra rule directories",
	"pref.dirs.desc": "Additional directories scanned for rule files, besides the global and project ones.",
	"pref.dirs.label": "Directories",
	"pref.dirs.placeholder": "One directory per line; ~ is expanded",
	"pref.reset": "Restore defaults",
	"pref.resetDone": "Defaults restored",
	"mem.list.title": "Memories",
	"mem.list.desc": "Browsed in store order; with a search term the ranking is the retrieval engine’s, the same one a session sees.",
	"mem.list.empty": "No memory matches this filter.",
	"mem.search": "Search",
	"mem.search.placeholder": "Type a keyword to rank by relevance",
	"mem.filter.scope": "Layer",
	"mem.filter.status": "Status",
	"mem.filter.project": "Project",
	"mem.total": "Total",
	"mem.more": "Load more",
	"mem.pin": "Pin",
	"mem.unpin": "Unpin",
	"mem.pinned": "Pinned",
	"mem.unpinned": "Unpinned",
	"mem.edit": "Edit",
	"mem.archive": "Archive",
	"mem.archived": "Archived",
	"mem.saved": "Saved",
	"mem.field.title": "Title",
	"mem.field.text": "Text",
	"mem.field.tags": "Tags",
	"mem.field.tags.desc": "Comma separated; tags appear in the panel’s tag list.",
	"add.title": "New memory",
	"add.desc": "The same write path the conversational remember tool uses: the same dedup, the same four-state merge.",
	"add.field.title": "Title (optional)",
	"add.field.title.placeholder": "Leave empty to derive one from the text",
	"add.field.text": "What should be remembered",
	"add.field.text.desc": "Facts and conclusions are enough; distillation does not need whole sentences.",
	"add.field.scope": "Target layer",
	"add.field.scope.desc": "The project layer needs a project; the identity layer is not edited here.",
	"add.field.project.pick": "Choose a project",
	"add.field.pinned": "Pin",
	"add.field.pinned.desc": "Pinned memories come first in the index and are never pruned.",
	"add.saved": "Stored",
	"add.note": "The panel calls no model: what you type is what is offered to the store, and whether it replaces something is the merge rule’s decision.",
	"add.decision": "Decision",
	"add.superseded": "Superseded",
	"daily.title": "Daily log",
	"daily.desc": "The fourth layer: what a finished turn appends, plus anything you add here by hand.",
	"daily.field.date": "Date",
	"daily.field.project": "Project",
	"daily.field.project.desc": "Leave empty for the global log.",
	"daily.empty": "No log for this day yet.",
	"daily.entries": "Entries",
	"daily.append": "Append",
	"daily.append.desc": "One entry per line; blank lines are ignored.",
	"daily.field.entry": "What to append",
	"daily.field.entry.desc": "One entry per line, appended in order.",
	"daily.saved": "Added to the log",
	"data.export.title": "Markdown export",
	"data.export.desc": "SQLite is the only storage format; Markdown exists for handover and for reading.",
	"data.export.archived": "Include archived and outdated rows",
	"data.export.archived.desc": "By default only memories still in force are exported.",
	"data.export.build": "Build",
	"data.export.download": "Download",
	"data.export.ready": "Built",
	"data.import.title": "Import from other tools",
	"data.import.desc": "Sources are recognised by content shape: ChatGPT, claude.ai, Claude Code, ZCode, WorkBuddy and others.",
	"data.import.path": "Path",
	"data.import.path.desc": "An export directory or a zip file; preview first to see exactly what would happen.",
	"data.import.path.placeholder": "e.g. C:\\Users\\me\\.workbuddy",
	"data.import.dry": "Preview only",
	"data.import.dry.desc": "Scan and decide without writing anything.",
	"data.import.scope": "Target layer",
	"data.import.preview": "Preview",
	"data.import.run": "Import",
	"data.import.done": "Import finished",
	"data.report.ok": "Recognised",
	"data.report.failed": "Not recognised",
	"data.report.dry": "Dry run",
	"data.report.truncated": "Truncated",
	"data.field.scanned": "Scanned",
	"data.field.considered": "Considered",
	"data.field.known": "Already known",
	"data.field.written": "Written",
	"data.field.wouldWrite": "Would write",
	"data.field.merged": "Merged",
	"data.field.updated": "Updated",
	"data.field.ignored": "Ignored",
	"data.field.rejected": "Rejected",
	"data.field.oversized": "Oversized",
	"data.field.logged": "Logged"
};
